version: '3.7'
services:
  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo-db
    #volumes:
      #- ./db/:/data/db
  test-bnext-transactional-api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: test-bnext-transactional-api
    links:
      - mongo-db